-- MySQL Script generated by MySQL Workbench
-- Fri Mar 19 21:26:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test-site-users
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test-site-users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test-site-users` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `test-site-users` ;

-- -----------------------------------------------------
-- Table `test-site-users`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test-site-users`.`users` (
  `user-id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(40) NOT NULL,
  `date-of-birth` DATE NOT NULL,
  `sex` BIT(1) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `authorized` BIT(1) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ``  NULL,
  ``  NOT NULL,
  ``  NULL,
  ``  NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`user-serial-number`));
  
  INSERT INTO users (user-id, name, surname, date-of-birth, sex, email, password,
  authorized) values (1, "Nickolay", Fokin, 1980-03-24, m, 








SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
